name: cyclonestef
favicon: null
layout_spectrum: 0.26918
typography_spectrum: 0.72159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5c6c8'
    - '#4b4b4d'
    - '#7d7e80'
    - '#fdfeff'
    - '#0f0d0e'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
